language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
notifications:
  email: false
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1
matrix:
  exclude:
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.0.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=3.1.1
