language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=2.6.17
  - PUPPET_VERSION=2.7.21
  - PUPPET_VERSION=3.0.2
  - PUPPET_VERSION=3.1.1
  - PUPPET_VERSION=3.2.1
matrix:
  exclude:
    - rvm: 1.9.2
      env: PUPPET_VERSION=2.6.17
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.6.17
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.6.17
