language: ruby
script: "bundle exec rake spec SPEC_OPTS='--color --format documentation'"
notifications:
  email: false
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.2
env:

  - PUPPET_VERSION=3.6.2
  - PUPPET_VERSION=3.7.1
